name: sftp_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.6
  dartssh3: ^3.0.0
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^4.2.1
  flutter_secure_storage_windows: ^3.1.2
  google_fonts: ^6.2.1
  path_provider: ^2.1.4
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_generator: ^2.4.0
  test: ^1.25.2

flutter:
  uses-material-design: true
